runtime: nodejs18

env_variables:
  RECYECO_DB: "recyeco-be"
  RECYECO_DB_USER: "recyeco"
  RECYECO_DB_PASSWORD: "recyeco"
  RECYECO_DB_HOST: "/cloudsql/inspiring-radar-419006:us-central1:recyeco-be"

handlers:
  - url: /.*
    script: auto
